spring:
  zipkin:
    base-url: http://localhost:9411
  zipkin:
    sender:
      type: web  #如果项目里引入了RabbitMQ依赖仍希望使用http方式发送数据，增加配置
  sleuth:
    sampler:
      probability: 1  # 设置抽样采集为100%，默认为0.1，即10%      
base-name: summer5
